<?php
/**
 * User: chenyi
 * Date: 15/9/24
 * Time: 17:54
 */

namespace app\modules\admin\controllers;

use app\helpers\DateFormat;
use app\helpers\Excel;
use app\helpers\ImagickHelper;
use app\models\Order;
use app\models\Period;
use app\models\Product;
use app\models\ProductCategory;
use app\models\ShareComment;
use app\models\ShareReply;
use app\models\User;
use app\modules\admin\models\Admin;
use Yii;
use yii\web\NotFoundHttpException;
use app\models\ShareTopic;
use app\models\ShareTopicImage;
use yii\helpers\ArrayHelper;
use app\models\Image;
use app\services\User as ServiceUser;
use app\helpers\Ex;

class ShareController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo '后台晒单列表功能关闭';
        Yii::$app->end();
    }

    //晒单列表
    public function actionIndex()
    {
        $is_pass = Yii::$app->request->get('is_pass', '-1');
        $start_time = Yii::$app->request->get('start_time', '');
        $end_time = Yii::$app->request->get('end_time', '');
        $account = Yii::$app->request->get('account', '');
        $is_recommend = Yii::$app->request->get('is_recommend', '-1');
        $get = Yii::$app->request->get();
        $condition = ['is_pass' => $is_pass, 'start_time' => $start_time, 'end_time' => $end_time, 'account' => $account, 'is_recommend' => $is_recommend];

        if ($start_time != '') {
            $start_time = strtotime($start_time);
        }
        if ($end_time != '') {
            $end_time = strtotime($end_time);
        }

        $where = [
            'is_pass' => $is_pass,
            'start_time' => $start_time,
            'end_time' => $end_time,
            'is_recommend' => $is_recommend,
            'account' => $account
        ];

        if(isset($get['excel']) && $get['excel'] == 'share'){
            $data = [];
            $page = isset($get['page']) ? $get['page'] : 1;
            $list = ShareTopic::adminShareTopicList($where, $page, PHP_INT_MAX);
            $data[0] = ['id'=>'ID', 'name'=>'商品名称', 'phone'=>'手机', 'email'=>'邮箱','point'=>'奖励福分','up_num'=>'羡慕','comment_num'=>'回复','recommand'=>'推荐', 'digest'=>'精华','status'=>'状态', 'time'=>'时间'];
            foreach($list['list'] as $key => $val){
                $key = $key +1;
                $data[$key]['id'] = $val['id'];
                $data[$key]['name'] = $val['name'];
                $data[$key]['phone'] = $val['phone'];
                $data[$key]['email'] = $val['email'];
                $data[$key]['point'] = $val['point'];
                $data[$key]['up_num'] = $val['up_num'];
                $data[$key]['comment_num'] = $val['comment_num'];
                if($val['is_recommend'] == 1) $is_recommend = '是';else $is_recommend = '否';
                $data[$key]['recommand'] = $is_recommend;
                if($val['is_digest'] == 1) $is_digest = '是';else $is_digest = '否';
                $data[$key]['digest'] = $is_digest;
                if($val['is_pass'] == 0){
                    $pass = '待审核';
                }elseif($val['is_pass'] == 1){
                    $pass = '完成';
                }elseif($val['is_pass'] == 2){
                    $pass = '未通过';
                }
                $data[$key]['status'] = $pass;
                $data[$key]['time'] = DateFormat::microDate($val['created_at']);
            }
            $excel = new Ex();
            $excel->download( $data, '晒单订单-'.date('Y-m-d H:i:s').'.xls');
        }

        $shareTopicList = ShareTopic::adminShareTopicList($where);

        if(empty($get)){
            $url = Yii::$app->request->getUrl().'?excel=share';
        }else{
            $url = Yii::$app->request->getUrl().'&excel=share';
        }

        return $this->render('index', [
            'condition' => $condition,
            'shareTopicList' => $shareTopicList['list'],
            'pagination' => $shareTopicList['pagination'],
            'url' => $url
        ]);
    }

    //晒单详情
    public function actionView()
    {
        $request = Yii::$app->request;
        $id = $request->get('id');
        $model = ShareTopic::findOne($id);

        if (!$model) {
            throw new NotFoundHttpException("页面未找到");
        }

        if($request->isPost){
            $post = $request->post();
            //$result = ShareTopic::updateTopic($model, $post);
            $result = ShareTopic::check($id, $post);
            if (is_array($result)) {
                return json_encode(['code' => 101, 'msg' => $result['msg']]);
            } elseif ($result === true) {
                return json_encode(['code' => 100]);
            } else {
                return json_encode(['code' => 101, 'msg' => '保存失败']);
            }
        }

        //获取图片
        $shareTopicImage = ShareTopicImage::findAll(['share_topic_id' => $id]);
        $shareTopicImage = ArrayHelper::toArray($shareTopicImage);
        foreach ($shareTopicImage as &$image) {
            $image['url'] = Image::getShareInfoUrl($image['basename'], 'share');
        }

        $admin = Admin::findOne($model['admin_id']);
        $model->admin_id = isset($admin['username']) ? $admin['username'] : '';

        //获取商品信息
        $data['productInfo'] = Product::findOne($model->product_id);
        //获取分类信息
        $data['categoryInfo'] = ProductCategory::findOne($model->cat_id);
        //获取期数信息
        $data['periodInfo'] = Period::findOne($model->period_id);
        //订单信息
        $data['orderInfo'] = Order::findOne(['period_id' => $model->period_id]);
        //用户信息
        $data['userInfo'] = User::findOne($model->user_id);
        $data['pictures'] = $shareTopicImage;
        $data['shareTopicInfo'] = $model;

        return $this->render('view', $data);
    }

    public function actionShowPicture()
    {
        $request = Yii::$app->request;
        $id = $request->get('id');
        $basename = $request->get('basename');
        $url = Image::getShareInfoUrl($basename, 'share');
        $imagePath = Image::getShareInfoFullPath($basename, 'share');
        $imagePath = \Yii::$app->sftp->getSFtpPath($imagePath);
        $sourceSize = getimagesize($imagePath);
        $width = 300;
        $height = ceil($sourceSize[1] * $width / $sourceSize['0']);
        return $this->render('picture', [
            'share_topic_id' => $id,
            'basename' => $basename,
            'url' => $url,
            'height' => $height,
            'width' => $width,
            'orgheight' => $sourceSize[1],
            'orgwidth' => $sourceSize[0]]
        );
    }

    //晒单删除
    public function actionDel()
    {
        $id = Yii::$app->request->post('id');
        $model = ShareTopic::findOne($id);
        $delete = $model->delete();
        if ($delete) {
            echo json_encode(['error' => 0, 'message' => '删除成功']);
        } else {
            echo json_encode(['error' => 1, 'message' => '删除成功']);
        }
    }

    //晒单推荐
    public function actionSetRecommend()
    {
        $request = Yii::$app->request;

        if ($request->isGet) {
            $id = $request->get('id');
            $op = $request->get('op');

            if ($op == 'cancel') {
                $where['id'] = $id;
                $where['is_recommend'] = 1;
            } else {
                $where['id'] = $id;
            }

            $model = ShareTopic::findOne($where);
            if ($model->is_recommend == 0 && !$model->recommend_image) {
                echo "<script>alert('请先设置推荐图');history.back();</script>";
                Yii::$app->end();
            }

            if ($model) {
                if ($op) {
                    $model->is_recommend = 0;
                } else {
                    $model->is_recommend = 1;
                    $model->recommended_at = time();
                }

                $model->save();
                return $this->redirect(Yii::$app->request->referrer);
            }
        }else{
            throw new NotFoundHttpException("页面未找到");
        }
    }

    //晒单精华
    public function actionSetDigest()
    {
        $request = Yii::$app->request;

        if ($request->isGet) {
            $id = $request->get('id');
            $op = $request->get('op');

            if ($op == 'cancel') {
                $where['id'] = $id;
                $where['is_digest'] = 1;
            } else {
                $where['id'] = $id;
            }

            $model = ShareTopic::findOne($where);

            if ($model) {
                if ($op) {
                    $model->is_digest = 0;
                } else {
                    $model->is_digest = 1;
                    $model->digested_at = time();
                }

                $model->save();
                return $this->redirect(Yii::$app->request->referrer);
            }
        }else{
            throw new NotFoundHttpException("页面未找到");
        }
    }

    //晒单审核
    public function actionVerify(){
        $id = Yii::$app->request->get('id');
        $model = ShareTopic::findOne($id);
        if($model){
            $isPass = Yii::$app->request->get('is_pass');
            if($isPass){
                $model->is_pass = $isPass;
                $model->save();
                return $this->redirect(Yii::$app->request->referrer);
            }else{
                if($model['is_pass'] == 1){
                    $model->is_pass = 2;
                }elseif($model['is_pass'] == 2){
                    $model->is_pass = 1;
                }
                $model->save();
                return $this->redirect(Yii::$app->request->referrer);
            }

        }
    }

    public function actionCommentList()
    {
        $share_topic_id = Yii::$app->request->get('id');
        $start_time = Yii::$app->request->post('start_time', '');
        $end_time = Yii::$app->request->post('end_time', '');
        $account = Yii::$app->request->post('account', '');
        $condition = ['start_time' => $start_time, 'end_time' => $end_time, 'account' => $account];

        if ($start_time != '') {
            $start_time = strtotime($start_time);
        }
        if ($end_time != '') {
            $end_time = strtotime($end_time . ' 23:59:59');
        }

        $shareCommentList = ShareComment::adminCommentList($share_topic_id, $start_time, $end_time, $account);

        return $this->render('commentlist', [
            'condition' => $condition,
            'list' => $shareCommentList['list'],
            'pagination' => $shareCommentList['pagination']
        ]);
    }

    public function actionReplyList()
    {
        $share_comment_id = Yii::$app->request->get('id');
        $start_time = Yii::$app->request->post('start_time', '');
        $end_time = Yii::$app->request->post('end_time', '');
        $account = Yii::$app->request->post('account', '');
        $condition = ['start_time' => $start_time, 'end_time' => $end_time, 'account' => $account];

        if ($start_time != '') {
            $start_time = strtotime($start_time);
        }
        if ($end_time != '') {
            $end_time = strtotime($end_time . ' 23:59:59');
        }

        $shareReplyList = ShareReply::adminReplyList($share_comment_id, $start_time, $end_time, $account);

        return $this->render('replylist', [
            'condition' => $condition,
            'list' => $shareReplyList['list'],
            'pagination' => $shareReplyList['pagination']
        ]);
    }

    public function actionSetPicture()
    {
        $basename = Yii::$app->request->get('basename');
        $shareTopicId = Yii::$app->request->get('share_topic_id');
        $size = Yii::$app->request->get('size');
        $sourceFilePath = Image::getShareInfoFullPath($basename, 'share');//原图路径
        $sourceFilePath = Yii::$app->sftp->getSFtpPath($sourceFilePath);
        $params['angle'] = Yii::$app->request->get('angle');
        $params['x'] = Yii::$app->request->get('x');
        $params['y'] = Yii::$app->request->get('y');
        $params['w'] = Yii::$app->request->get('w');
        $params['h'] = Yii::$app->request->get('h');

        if ($size == 'detail') {
            Image::createShareInfoImage($sourceFilePath, $basename, 'big', [
                    'text' => 'www.huogou.com    www.huogou.com    www.huogou.com    www.huogou.com    www.huogou.com    www.huogou.com',
                    'angle' => -30,
                    'font_size' => 40,
                    'fill_color' => '#fff',
                    'fill_opacity' => 0.2]
            );
            Image::createShareInfoImage($sourceFilePath, $basename, 'small', [
                    'text' => 'www.huogou.com    www.huogou.com    www.huogou.com    www.huogou.com    www.huogou.com',
                    'angle' => -30,
                    'font_size' => 10,
                    'fill_color' => '#fff',
                    'fill_opacity' => 0.2]
            );
            return 1;
        }

        $newbasename = Image::generateName() . '.jpg';
        $trans = Yii::$app->db->beginTransaction();
        try {
            $shareTopicImage = ShareTopicImage::findOne(['basename' => $basename, 'share_topic_id' => $shareTopicId]);
            $shareTopic = ShareTopic::findOne($shareTopicId);

            if ($size == 'main') {
                $delname = $shareTopic->header_image;
                $shareTopic->header_image = $newbasename;
                $shareTopicImage->main = 1;
            } elseif ($size == 'roll') {
                $delname = $shareTopic->roll_image;
                $shareTopic->roll_image = $newbasename;
                $shareTopicImage->roll = 1;
            } elseif ($size == 'recommend') {
                $delname = $shareTopic->recommend_image;
                $shareTopic->recommend_image = $newbasename;
                $shareTopicImage->recommend = 1;
            } elseif ($size == 'mobile') {
                $shareTopicImage->mobile = 1;
            }

            ShareTopicImage::updateAll([$size => 0], ['share_topic_id' => $shareTopicId]);

            if (!$shareTopic->save()) {
                $trans->rollBack();
                return 0;
            }

            if (!$shareTopicImage->save()) {
                $trans->rollBack();
                return 0;
            }

            if ($delname) {
                Image::deleteShareInfoImage($delname);
            }

            Image::createShareInfoImage($sourceFilePath, $newbasename, $size, $params);
            $trans->commit();
            return 1;
        } catch (Exception $e) {
            $trans->rollBack();
            return 0;
        }
    }

    public function actionEditComment()
    {
        $shareCommentId = Yii::$app->request->get('id');
        $shareComment = ShareComment::findOne($shareCommentId);

        if(Yii::$app->request->isPost){
            $post = Yii::$app->request->post();
            $shareComment->content = $post['content'];
            if ($shareComment->save()) {
                return 1;
            } else {
                return 0;
            }
        }

        return $this->render('editcomment', ['shareComment' => $shareComment]);
    }

    public function actionEditReply()
    {
        $shareReplyId = Yii::$app->request->get('id');
        $shareReply = ShareReply::findOne($shareReplyId);

        if(Yii::$app->request->isPost){
            $post = Yii::$app->request->post();
            $shareReply->content = $post['content'];
            if ($shareReply->save()) {
                return 1;
            } else {
                return 0;
            }
        }

        return $this->render('editreply', ['shareReply' => $shareReply]);
    }

    public function actionDeleteComment()
    {
        $shareCommentId = Yii::$app->request->get('id');
        ShareComment::deleteAll(['id' => $shareCommentId]);
        ShareReply::deleteAll(['share_comment_id' => $shareCommentId]);
        return 1;
    }

    public function actionDeleteReply()
    {
        $shareReplyId = Yii::$app->request->get('id');
        ShareReply::deleteAll(['id' => $shareReplyId]);
        return 1;
    }

}