CREATE TABLE `act_rich_log` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` INT(10) UNSIGNED DEFAULT 0 NOT NULL COMMENT '用户',
  `money` INT(10) UNSIGNED DEFAULT 0 NOT NULL COMMENT '消费金额',
  `type` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1天，2周，3月',
  `rank` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '排名',
  `time` VARCHAR(50) NOT NULL COMMENT '时间',
  `created_at` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`user_id`)
)ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT='土豪榜记录';