CREATE TABLE `act_orders` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `name` VARCHAR (255) NOT NULL COMMENT '商品名称',
  `picture` VARCHAR(255) NOT NULL COMMENT '封面图,带后缀的图片名',
  `act_type` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '活动类型，1=抽奖奖品，2=0元购,3=月土豪',
  `act_obj_id` INT(10) NOT NULL DEFAULT '0' COMMENT '活动类型对象ID',
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT '用户ID',
  `status` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '订单状态',
  `confirm` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '确认状态',
  `ship_name` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '收货人',
  `ship_zip` varchar(20) NOT NULL DEFAULT '' COMMENT '收货人邮编',
  `ship_area` varchar(255) NOT NULL DEFAULT '' COMMENT '收货地区',
  `ship_addr` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '收货地址',
  `ship_mobile` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '收货人手机',
  `ship_email` varchar(200) NOT NULL DEFAULT '' COMMENT '收货人email',
  `ship_time` varchar(25) NOT NULL DEFAULT '' COMMENT '配送时间',
  `mark_text` TEXT COMMENT '订单备注',
  `remark` TEXT COMMENT '管理员订单备注',
  `create_time` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `confirm_addr_time` int(10) NOT NULL DEFAULT '0' COMMENT '确认收货地址时间',
  `confirm_goods_time` int(10) NOT NULL DEFAULT '0' COMMENT '确认收货时间',
  `last_modified` INT(10) UNSIGNED NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`, `create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8 COMMENT '活动中奖订单';