CREATE TABLE `duiba_orders_100` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_101` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_102` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_103` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_104` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_105` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_106` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_107` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_108` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';

CREATE TABLE `duiba_orders_109` (
  `id` CHAR(25) NOT NULL COMMENT '订单ID',
  `user_id` INT(11) NOT NULL COMMENT '用户Id',
  `order_no` CHAR(25) NOT NULL COMMENT '中奖订单号',
  `credits` INT(10) NOT NULL DEFAULT '0' COMMENT '本次兑换扣除的积分',
  `appKey` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '接口appKey',
  `timestamp` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '时间戳',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本次积分消耗的描述',
  `order_num` VARCHAR(255)  NOT NULL COMMENT '兑吧订单号',
  `type` VARCHAR(255)  NOT NULL COMMENT '兑换类型：alipay(支付宝), qb(Q币),phonebill(话费)',
  `face_price` INT(11) UNSIGNED NOT NULL COMMENT '兑换商品的市场价值，单位是分',
  `actual_price` INT(11) UNSIGNED NOT NULL COMMENT '此次兑换实际扣除开发者账户费用，单位是分',
  `ip` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT 'IP',
  `wait_audit` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '是否需要审核',
  `audit_status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1' COMMENT '审核状态',
  `params` VARCHAR(255)  NOT NULL DEFAULT '' COMMENT '详情参数，不同的类型，返回不同的内容',
  `sign` VARCHAR(255)NOT NULL COMMENT '签名',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '状态,兑换成功失败',
  `error_msg` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出错信息',
  `created_at` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '兑吧订单';