CREATE TABLE `pk_orders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `product_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '商品ID',
  `period_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '期数ID',
  `desk_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '卓号',
  `ship_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '发货状态',
  `is_virtual` int(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否是虚拟物品',
  `shipping_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '配送方式ID',
  `shipping` varchar(100) NOT NULL DEFAULT '' COMMENT '配送方式',
  `user_id` int(10) unsigned NOT NULL COMMENT '用户ID',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单状态',
  `confirm` tinyint(1) NOT NULL DEFAULT '0' COMMENT '确认状态',
  `ship_mobile` varchar(25) NOT NULL DEFAULT '' COMMENT '收货人手机',
  `price` int(10) NOT NULL COMMENT '订单商品价格',
  `memo` text COMMENT '订单附言',
  `mark_text` text COMMENT '订单备注',
  `fail_type` tinyint(2) DEFAULT NULL COMMENT '订单失败类型，1驳回填写地址，2发货异常，3无法送达，4换货原因',
  `fail_id` varchar(255) DEFAULT '0' COMMENT '失败原因',
  `create_time` int(10) unsigned NOT NULL COMMENT '创建时间',
  `last_modified` int(10) unsigned DEFAULT NULL COMMENT '最后更新时间',
  `confirm_addr_time` int(10) NOT NULL DEFAULT '0' COMMENT '确认收货地址时间',
  `confirm_goods_time` int(10) NOT NULL DEFAULT '0' COMMENT '确认收货时间',
  `remark` text COMMENT '备注',
  `push_msg` smallint(2) NOT NULL DEFAULT '0' COMMENT '中奖信息是否已推送',
  `delay` int(11) DEFAULT '0' COMMENT '设置异常时间',
  `before_status` tinyint(2) DEFAULT '0' COMMENT '设置异常前状态',
  `size` tinyint(1) NOT NULL DEFAULT '0' COMMENT '大小',
  `is_buyback` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否回购 0不回购 1回购',
  `ship_addr` varchar(255) NOT NULL DEFAULT '' COMMENT '收货地址',
  `ship_zip` varchar(20) NOT NULL DEFAULT '' COMMENT '收货邮编',
  `ship_email` varchar(25) NOT NULL DEFAULT '' COMMENT '收货人email',
  `ship_time` varchar(25) NOT NULL DEFAULT '' COMMENT '配送时间',
  `ship_area` varchar(25) NOT NULL DEFAULT '' COMMENT '收货地区',
  `ship_name` varchar(25) NOT NULL DEFAULT '' COMMENT '收货人',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Pk活动中奖订单';