CREATE TABLE `qq` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `num` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'qq号',
  `default` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认',
  `android_key` VARCHAR(255) NOT NULL COMMENT '安卓key',
  `ios_key` VARCHAR(255) NOT NULL COMMENT 'ios key',
  `uin` VARCHAR(255) NOT NULL COMMENT 'ios特有',
  `created_at` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `admin_id` INT(5) NOT NULL DEFAULT 0 COMMENT '创建人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='qq群';