<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "lottery_compute_100".
 *
 * @property integer $id
 * @property integer $period_id
 * @property string $data
 * @property string $expect
 * @property string $shishi_num
 */
class LotteryComputeDistribution extends \yii\db\ActiveRecord
{
    private static $_tableId;

    public static function instantiate($row)
    {
        return new static(static::$_tableId);
    }

    public function __construct($tableId, $config = [])
    {
        parent::__construct($config);
        static::$_tableId = $tableId;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        $tableId = substr(static::$_tableId, 0, 3);
        return 'lottery_compute_' . $tableId;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period_id'], 'integer'],
            [['data'], 'string'],
            [['expect'], 'string', 'max' => 12],
            [['shishi_num'], 'string', 'max' => 8],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'period_id' => 'Period ID',
            'data' => 'Data',
            'expect' => 'Expect',
            'shishi_num' => 'Shishi Num',
        ];
    }

    /**
     * @param $tableId
     * @return \yii\db\ActiveQuery the newly created [[ActiveQuery]] instance.
     */
    public static function findByTableId($tableId)
    {
        $model = new static($tableId);
        return $model::find();
    }

    /**
     * @param $tableId
     * @param $condition
     * @return \yii\db\ActiveRecord|null ActiveRecord instance matching the condition, or `null` if nothing matches.
     */
    public static function findOneByTableId($tableId, $condition)
    {
        $model = new static($tableId);
        return $model::findOne($condition);
    }

    /**
     * @param $tableId
     * @param $condition
     * @return \yii\db\ActiveRecord[] an array of ActiveRecord instances, or an empty array if nothing matches.
     */
    public static function findAllByTableId($tableId, $condition)
    {
        $model = new static($tableId);
        return $model::findAll($condition);
    }

    /**
     * @param $tableId
     * @param $attributes
     * @param string $condition
     * @param array $params
     * @return mixed
     */
    public static function updateAllByTableId($tableId, $attributes, $condition = '', $params = [])
    {
        $model = new static($tableId);
        return $model::updateAll($attributes, $condition, $params); // TODO: Change the autogenerated stub
    }
}
